services:
  webservicedemov1:
    build:
      context: .
      dockerfile: DockerFilev1
    container_name: webservicedemov1
    restart: always
    ports:
      - "8080:8080"
  webservicedemov2:
    build:
      context: .
      dockerfile: Dockerfilev2
    container_name: webservicedemov2
    restart: always
    ports:
      - "8081:8081"
