apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clt-kafka
spec:
  replicas: 1
  serviceName: clt-kafka
  selector:
    matchLabels:
      app: clt-kafka
  template:
    metadata:
      labels:
        app: clt-kafka
    spec:
      containers:
        - name: clt-kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 9101
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_JMX_PORT
              value: "9101"

---
apiVersion: v1
kind: Service
metadata:
  name: clt-kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: "9092"
    - port: 29092
      targetPort: 29092
      name: "29092"
  selector:
    app: clt-kafka