apiVersion: apps/v1
kind: Deployment
metadata:
  name: moteur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moteur
  template:
    metadata:
      labels:
        app: moteur
    spec:
      containers:
        - name: moteur
          image: cguillier/moteur:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/meow"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password1234"

---
apiVersion: v1
kind: Service
metadata:
  name: moteur
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: moteur